
n_threads: 4
random_seed: 1


genomes:
  # yeast
  sacCer3:
    remove_chr_prefix: False
    small:
      chromosomes: "chrI"
    medium:
      chromosomes: "chrI,chrII,chrIII,chrIV"
    big:
      chromosomes: "chrI,chrII,chrIII,chrIV,chrIX,chrV,chrVI,chrVII,chrVIII,chrX,chrXI,chrXII,chrXIII,chrXIV,chrXV,chrXVI,chrM"

  hg38:
    remove_chr_prefix: True
    small:
      chromosomes: 20,21
    medium:
      chromosomes: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10
    big:
      chromosomes: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22

  # simulated genome sequence
  simulated1:
    genome_size: 10000000
    n_chromosomes: 10

    simulated:
      simulated: True
      small:
        chromosomes: "chr1,chr2,chr3"



mason_variator_parameters:
   "--snp-rate 0.002
   --small-indel-rate 0.0005
   --min-small-indel-size 2
   --max-small-indel-size 25
   --sv-indel-rate 0
   --sv-inversion-rate 0
   --sv-translocation-rate 0
   --sv-duplication-rate 0
   "



real_datasets:
    1000genomes:
      chromosomes: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22"
      #chromosomes: "18,19,20,21,22"
