
n_threads: 4
random_seed: 1


genomes:
  # yeast
  sacCer3:
    remove_chr_prefix: False
    input_is_biallelic: True
    small:
      chromosomes: "chrI"
    medium:
      chromosomes: "chrI,chrII,chrIII,chrIV"
    big:
      chromosomes: "chrI,chrII,chrIII,chrIV,chrIX,chrV,chrVI,chrVII,chrVIII,chrX,chrXI,chrXII,chrXIII,chrXIV,chrXV,chrXVI,chrM"

  hg38:
    remove_chr_prefix: True
    input_is_biallelic: True
    small:
      chromosomes: "21"
    medium:
      chromosomes: "18,19,20,21"
    medium2:
      chromosomes: "1,2,3,4,5,6,7,8"
    medium3:
      chromosomes: "1,2,3,4"
    medium4:
      chromosomes: "16"
    medium5:
      chromosomes: "1,2,3,4,5"
    big:
      chromosomes: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22"

  chm13:
    remove_chr_prefix: False
    input_is_biallelic: False
    tiny:
      chromosomes: "chr21:0-20000000"
    small:
      chromosomes: "chr21"

  # simulated genome sequence
  simulated1:
    input_is_biallelic: True
    genome_size: 10000000
    n_chromosomes: 10

    simulated:
      simulated: True
      small:
        chromosomes: "chr1,chr2,chr3"



mason_variator_parameters:
   "--snp-rate 0.002
   --small-indel-rate 0.0005
   --min-small-indel-size 2
   --max-small-indel-size 25
   --sv-indel-rate 0
   --sv-inversion-rate 0
   --sv-translocation-rate 0
   --sv-duplication-rate 0
   "



real_datasets:
    1000genomes:
      chromosomes: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22"
      #chromosomes: "18,19,20,21,22"