
test_plots: [

]

# Default parameter groups. Will be used for plotting if not overridden in plot config in plots.yaml
default_parameter_sets:
  coverage: [1.0, 5.0, 10.0, 20.0]
  method: ["pangenie", "kage", "kage_no_imputation"]
  n_individuals: [5, 25, 50]
  variant_type: ["snps", "small_indels", "svs"]



# Axis/titles/etc that will be replaced in plots
pretty_names:
  ScaffolderAccuracy: Accuracy


# Plots
plots:
  generic:
    # used as a dummy for plots that are not defined
    plot_type: ""
  small_test:
    plot_type: accuracy
    parameters:
      individual_id: 1
      size: small
      coverage: [5.0, 10.0]
      n_individuals: [5, 10]

  test:
    plot_type: accuracy
    parameters:
      individual_id: simulated_1
      size: small

  test2:
    plot_type: accuracy
    parameters:
      size: "medium"
      coverage: [3.0, 7.0, 15.0, 30.0]
      n_individuals: [5, 25, 50]


  plot1:
    plot_type: f1_vs_n_individuals 
    parameters:
      size: small
      genome_build: hg38
      n_individuals: [5, 10, 50, 100, 500, 1000, 2000]
      variant_type: all
      allele_frequency_snps_indels: 0.01
      allele_frequency_svs: "0.00001"  # str to avoid scientific notation
      method: ["kage", "pangenie"]
    type_limits:
      source: RealVariantSource


# The following defines different type of plots
# This includes only the description of the structure of each plot, not what values are used for the variables
# Each of x_axis, y_axis, category_variable, color, labels, facet_col, facet_row
# should be either a result_type or a parameter_type if set

plot_types:

  accuracy:
    type: line
    x: coverage
    y: GenotypeF1Score
    color: method
    facet_col: n_individuals
    facet_row: variant_type

  f1_vs_n_individuals:
    type: line
    x: n_individuals
    y: GenotypeF1Score
    color: method
