
test_plots: [

]

# Default parameter groups. Will be used for plotting if not overridden in plot config in plots.yaml
default_parameter_sets:
  coverage: [1.0, 5.0, 10.0, 20.0]
  method: ["pangenie", "kage", "kage_no_imputation"]
  n_individuals: [5, 25, 50]
  variant_type: ["snps", "small_indels", "svs"]
  size: small
  genome_build: sacCer3
  snp_rate: 0.01
  small_indel_rate: 0.01
  sv_indel_rate: 0.005


# Axis/titles/etc that will be replaced in plots
pretty_names:
  ScaffolderAccuracy: Accuracy


# Plots
plots:
  generic:
    # used as a dummy for plots that are not defined
    plot_type: ""
  small_test:
    plot_type: accuracy
    parameters:
      individual_id: 1
      size: small
      coverage: [5.0, 10.0]
      n_individuals: [5, 10]

  test:
    plot_type: accuracy
    parameters:
      individual_id: simulated_1
      size: small

  test2:
    plot_type: accuracy
    parameters:
      size: "medium"
      coverage: [3.0, 7.0, 15.0, 30.0]
      n_individuals: [5, 25, 50]


  plot1:
    plot_type: f1_vs_n_individuals 
    parameters:
      size: small
      genome_build: hg38
      n_individuals: [5, 25, 60, 125, 500, 2500]
      variant_type: all
      allele_frequency_snps_indels: 0.01
      allele_frequency_svs: 0
      method: ["kage", "pangenie"]
      limit_accuracy_to_variant_type: ["snps", "indels", "svs", "all"]
    type_limits:
      source: RealVariantSource

  plot2:
    plot_type: f1_vs_n_individuals
    parameters:
      size: medium6
      genome_build: hg38
      n_individuals: [ 5, 50, 125, 500, 2500]
      variant_type: all
      allele_frequency_snps_indels: 0.01
      allele_frequency_svs: 0
      method: [ "kage", "pangenie", "paragraph" ]
      limit_accuracy_to_variant_type: [ "snps", "indels", "svs", "all" ]
    type_limits:
      source: RealVariantSource
    layout:
      xaxis_type: log

  plot3:
    plot_type: sv_accuracy_vs_snp_rate
    parameters:
      size: medium6
      genome_build: hg38
      n_individuals: 125
      variant_type: all
      allele_frequency_snps_indels: [0.0001, 0.001, 0.01, 0.1, 0.25, 0.5]
      allele_frequency_svs: 0
      method: [ "kage", "pangenie" ]
      limit_accuracy_to_variant_type: "svs"
    type_limits:
      source: RealVariantSource
    layout:
      xaxis_type: log

  plot3_simulated:
    plot_type: sv_accuracy_vs_snp_rate
    parameters:
      size: medium
      genome_build: sacCer3
      n_individuals: 50
      allele_frequency_snps_indels: [ 0.0001, 0.001, 0.01, 0.1, 0.25, 0.5 ]
      allele_frequency_svs: 0
      method: [ "kage" ]
      limit_accuracy_to_variant_type: "svs"
      snp_rate: 0.01
      small_indel_rate: 0.01
      sv_indel_rate: 0.005
      n_threads: 4
    type_limits:
      source: SimulatedPopulation
    layout:
      xaxis_type: log

  runtime_small:
    plot_type: runtime_vs_n_individuals
    parameters:
      size: small
      genome_build: sacCer3
      n_individuals: [5, 10, 50]
      method: ["kage", "pangenie"]
      n_threads: 8
      snp_rate: 0.01
      small_indel_rate: 0.01
      sv_indel_rate: 0.005
      #variant_type: "snps_indels"
    type_limits:
      source: SimulatedPopulation

  runtime:
    plot_type: runtime_vs_n_individuals
    parameters:
      size: small
      genome_build: hg38
      n_individuals: [5, 25, 50, 75, 100, 125, 150]
      method: ["kage", "pangenie"]
      n_threads: 4
      snp_rate: 0.01
      small_indel_rate: 0.01
      sv_indel_rate: 0.005
      variant_type: "all"
    type_limits:
      source: RealVariantSource

  read_error_rate:
    plot_type: accuracy_vs_read_error_rate
    parameters:
      n_individuals: 20
      method: ["kage", "pangenie"]
      snp_error_rate: [0.0, 0.0001, 0.001, 0.01, 0.1, 0.2, 0.4]
    type_limits:
      source: SimulatedPopulation


  # The following defines different type of plots
# This includes only the description of the structure of each plot, not what values are used for the variables
# Each of x_axis, y_axis, category_variable, color, labels, facet_col, facet_row
# should be either a result_type or a parameter_type if set

plot_types:

  accuracy:
    type: line
    x: coverage
    y: GenotypeF1Score
    color: method
    facet_col: n_individuals
    facet_row: variant_type

  f1_vs_n_individuals:
    type: line
    x: n_individuals
    y: GenotypeF1Score
    color: method
    facet_row: limit_accuracy_to_variant_type

  sv_accuracy_vs_snp_rate:
    type: line
    x: allele_frequency_snps_indels
    y: GenotypeF1Score
    color: method

  runtime_vs_n_individuals:
    type: line
    x: n_individuals
    y: GenotypeRuntime
    color: method
    text: n_threads
    #facet_col: n_threads

  accuracy_vs_read_error_rate:
    type: line
    x: snp_error_rate
    y: GenotypeF1Score
    color: method